version: '3'
name: Webbid Development

services:
  database:
    image: 'postgres:latest'

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - ${POSTGRES_PORT}:5432

  smtp-server:
    image: 'maildev/maildev'

    ports:
      - 1080:1080
      - 1025:1025
